### ISSUE TITLE
[Feature Request] Ability to show python package releases for python interpreter

### ISSUE THREAD

**Issue by gaborbernat** [wasi-master/pypi-command-line#10]
## Is your feature request related to a problem/bug/intentional feature? Please describe if it is.

Ability to view when your project dependencies have updated/changed.

## Describe the solution you'd like.

```bash
pypi history --python env/bin/python --limit 1

# nested tree entries for version when limit > 1 else inline at the root level for the tree
- X - 1.2.0 3 hours ago (Sat Oct 23 11:00:04 2021)
- A - 1.0.0 5 days ago (Sat Oct 23 11:00:04 2021) 
```

would display in reverse chronological order the latest release for all packages found in the `env/bin/python` interpreter. Bonus point for showing the last `n` releases, where `n` is a CLI argument.

**Comment by wasi-master** [comment]
So something like `pip freeze` but for the latest version rather than the installed version?

**Comment by gaborbernat** [comment]
It's more like a combination of `pip list --outdated` and reverse `pip freeze` 🤔. And would formulate it as the latest n version, rather than always latest, though by default could be just latest. If the local version is less than the latest display the release date of the local version and latest (in this case latest could be italic to show not yet installed). The idea is to see for a given interpreter what packages are out of date/up to date and when those versions have been released.

**Comment by wasi-master** [comment]
I see. I'll start working on it tomorrow. 

Although the name history seems a bit off to me :thinking:.

**Comment by gaborbernat** [comment]
Not sure what's a better name though.

**Comment by wasi-master** [comment]
After doing some research I figured that you can already do this with the [`version`](https://wasi-master.github.io/pypi-command-line/usage/#version) command combined with `pip list --outdated`

**Windows**
```posh
pip list --outdated --format=freeze | %{$_.split('==')[0]} | %{pypi version --limit 1 --no-pre-releases --show-installed-versions $_}
```
**Linux/MacOS**
```bash
pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n 1 pypi version --limit 1 --no-pre-releases --show-installed-versions
```

Notes:
* You need to update pypi-command-line to the latest version for the new arguments to work
    ```sh
    pip install -U pypi-command-line
    ```
* You can also save these to a script file (extension: `.bat` on windows and `.sh` on linux) and then run the file whenever you need to

**Comment by gaborbernat** [comment]
Would be nice if this would be supported out of box (even though can be worked around with various shell scripts).

**Comment by wasi-master** [comment]
The versions not being printed in chronological order is due to the order `pip list --outdated` displays them as. This as a command would be hard to implement since there is no direct way of getting all the installed packages, not really sure what to do

**Comment by gaborbernat** [comment]
Couldn't this app collect internally those versions and sort them before displaying?

**Comment by wasi-master** [comment]
Collect them how though, because I can't seem to find any way of doing that, most of the answers on stackoverflow are outdated. currently the only solution I can think of is to parse the output of pip list. I'll try to do that

**Comment by wasi-master** [comment]
As much as I would like to do this, this is currently a bit out of scope for this library because it would rely on running and parsing the output of `pip list --outdated` just to sort them and a sufficiently good solution already exists.

Running and parsing shell commands within python just to sort the output is a bit too convoluted for this library in my opinion

Sorry, Please don't mind :)

**Comment by gaborbernat** [comment]
That's fine thank you, created https://github.com/gaborbernat/pypi_changes that achieves what I mostly wanted.

**Comment by wasi-master** [comment]
@gaborbernat Great, Looking forward to that :))

**Comment by gaborbernat** [comment]
has been released now https://twitter.com/gjbernat/status/1456207118470684674 
![fyi](https://media.tenor.co/images/3a2f08291bfc97c431e54e8b0e714f85/tenor.gif)

**Comment by wasi-master** [comment]
@gaborbernat looks nice, good work!
