### ISSUE TITLE
[Feature Request] Support custom pypi registries

### ISSUE THREAD

**Issue by robross0606** [wasi-master/pypi-command-line#27]
## Is your feature request related to a problem/bug/intentional feature? Please describe if it is.
In many environments, users go to a proxy instead of directly to pypi.org.  They also may be supplementing internal packages in their private registries.  `pip` supports this by way of `.pypirc`, `pip.conf`/`pip.ini` and `$PIP_INDEX_URL`, but this project seems to ignore those settings and always uses pypi.org. 

## Describe the solution you'd like.
Ideally, the project would pay attention to the same configuration as `pip` and check the expected repositories instead of always using pypi.org.

## Describe alternatives you've considered if there are any.
A direct command-line switch to override the repository URL would be marginally useful in lieu of directly using `pip` config files.

## Additional context if applicable
You can see what `pip` checks by calling `pip config list -v`:
```
# pip config list -v
For variant 'global', will try loading '/etc/xdg/pip/pip.conf'
For variant 'global', will try loading '/etc/pip.conf'
For variant 'user', will try loading '/home/user/.pip/pip.conf'
For variant 'user', will try loading '/home/user/.config/pip/pip.conf'
For variant 'site', will try loading '/usr/pip.conf'
```

**Comment by wasi-master** [comment]
You mean support for alternative registries like test.pypi.org (and others)?

**Comment by robross0606** [comment]
Yes, alternate registries including ones that are not necessarily publicly accessible.

**Comment by wasi-master** [comment]
Possible via the [`--repository`](https://wasimaster.me/pypi-command-line/usage/#-repository) flag
